import type { Project } from '@/types';

export const projects: Project[] = [
  {
    id: 1,
    title: 'Blomac Custom PC Builder',
    description: 'Advanced e-commerce platform for custom PC building with real-time compatibility checks, AI-powered recommendations for gamers and professionals, wishlist, product comparison, and secure Razorpay checkout.',
    image: '�',
    tags: ['Next.js 15', 'React 18', 'Firebase', 'Razorpay', 'Tailwind CSS', 'Radix UI', 'Framer Motion'],
    category: 'web',
    featured: true,
    github: 'https://github.com/techjunior2022',
    live: 'https://blomaccustompc.in',
    stats: { stars: 45, forks: 12 },
  },
  {
    id: 2,
    title: 'HexStrike AI MCP Agents',
    description: 'Advanced Model Context Protocol (MCP) server connecting AI agents with 150+ cybersecurity tools. Automates penetration testing, vulnerability discovery, bug bounty workflows, and security research in authorized environments.',
    image: '🤖',
    tags: ['Python', 'AI', 'MCP', 'Automation', 'Security Tools', 'LLM Integration'],
    category: 'ai',
    featured: true,
    github: 'https://github.com/techjunior2022/hexstrike-ai',
    live: '#',
    stats: { stars: 87, forks: 21 },
  },
  {
    id: 3,
    title: 'Dot Defence Security Platform',
    description: 'Comprehensive cybersecurity service platform offering penetration testing, VAPT services, security audits, digital forensics, and AI-powered threat analysis for businesses and startups.',
    image: '🛡️',
    tags: ['Next.js', 'TypeScript', 'Cybersecurity', 'VAPT', 'Security Audits'],
    category: 'web',
    featured: true,
    github: 'https://github.com/techjunior2022',
    live: '#',
    stats: { stars: 38, forks: 9 },
  },
  {
    id: 4,
    title: 'Security Audit Dashboard',
    description: 'Automated vulnerability scanning dashboard with real-time threat detection, compliance reporting (ISO 27001, PCI DSS), and risk assessment visualization.',
    image: '📊',
    tags: ['React', 'Python', 'Burp Suite API', 'Nessus', 'Chart.js', 'Security'],
    category: 'web',
    github: 'https://github.com/techjunior2022',
    live: '#',
    stats: { stars: 23, forks: 7 },
  },
  {
    id: 5,
    title: 'CTF Challenge Platform',
    description: 'Capture The Flag platform for hosting cybersecurity challenges, featuring web exploitation, steganography, cryptography, and OSINT challenges with real-time scoring.',
    image: '�',
    tags: ['Next.js', 'Docker', 'Python', 'CTF', 'Security'],
    category: 'web',
    github: 'https://github.com/techjunior2022',
    live: '#',
    stats: { stars: 56, forks: 15 },
  },
  {
    id: 6,
    title: 'Red Team Automation Toolkit',
    description: 'Collection of Python scripts for red team operations including reconnaissance, vulnerability exploitation, post-exploitation, and reporting automation.',
    image: '⚔️',
    tags: ['Python', 'Bash', 'Red Teaming', 'Automation', 'Pentesting'],
    category: 'ai',
    github: 'https://github.com/techjunior2022',
    stats: { stars: 34, forks: 11 },
  },
];

// Project statistics for display
export const projectStats = [
  { value: projects.length, label: 'Total Projects' },
  { value: '20+', label: 'Technologies Used' },
  { value: projects.filter(p => p.live).length, label: 'Live Demos' },
  { value: '100%', label: 'Open Source' },
];
